name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
      - uses: actions/checkout@v4
      - run: tools/ci/setup.sh
      - run: cargo build --all-features
  test:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
      - uses: actions/checkout@v4
      - run: tools/ci/setup.sh
      - run: cargo test --all-features
  bench:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
      - uses: actions/checkout@v4
      - run: tools/ci/setup.sh
      - run: cargo bench
  dialect_build:
    # TODO Remove this job when refactoring of dialect macros is done.
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
      - uses: actions/checkout@v4
      - run: tools/ci/setup.sh
      - run: cargo install cargo-expand
      - run: cd melior && cargo expand --features ods-dialects > ~/current.rs
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: cd melior && cargo expand --features ods-dialects > ~/main.rs
      - run: diff ~/main.rs ~/current.rs
